### ISSUE TITLE
Import framework into Xcode Not Working

### ISSUE THREAD

**Issue by sekkit** [gregneagle/relocatable-python#1]
inside Xcode, Python.Framework's Headers can't be opened.

**Comment by gregneagle** [comment]
That’s not a need I have. I imagine you’d have the same problem with the downloads from Python.org, no?

**Comment by sekkit** [comment]
yes, I used your MOD version, /bin/python3 xxxx to run program instead of embedding to Xcode.

**Comment by gregneagle** [comment]
Closing as not something we support.
