### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by njsmith** [gregneagle/relocatable-python#18]
Hello!

I've been poking at the idea of distributing pre-built python environments in an automation-friendly way, with the eventual goal of making them a standard thing that are distributed on PyPI, so tools like `pyenv` and `tox` can grab arbitrary pre-built Python binaries whenever they need them. So far I have the beginnings of a [tox-like tool](https://github.com/njsmith/posy/blob/main/pybi/README.md) that could use them, and a [draft spec](https://github.com/njsmith/posy/blob/main/pybi/README.md) for the file format, and I figure to start with I'll making some binaries in this format for linux/windows/macos and stick them somewhere to demonstrate that it works and is useful, before trying to convince the pypi folks and cpython release managers to get on board.

I think I've figured out how to make standalone relocatable cpython builds on linux and windows... but I'm pretty clueless about macos, don't have easy access to a macos system, and don't have a developer ID or anything like that. (Which I think you need to distribute binaries these days, because of notarization and apple silicon, something something? Maybe? You see how clueless I am.) But! It seems like you have the macos stuff pretty figured out, and are also looking for a way to get some traction for these kinds of builds in the community, so you don't have to keep maintaining this on your own forever.

Perhaps we should join forces to ~~rule the galaxy~~provide cpython binaries and try to make this a thing?

**Comment by gregneagle** [comment]
I know next to zero about PyPi, pyenv and tox, and don't really use any of those.
If you don't have easy access to a macOS system, I think you are going to struggle with the macOS end of this.

I'm not really looking for "a way to get some traction for these kinds of builds in the community". This tool solves a problem for me, and I've shared it in case it might solve a similar problem for others. But if no-one else uses it, that's fine, too.

**Comment by njsmith** [comment]
Ah well, too bad.
