### ISSUE TITLE
Switch to #!/usr/bin/env python3 to work with Monterey 12.3

### ISSUE THREAD

**Issue by Keith969** [gregneagle/relocatable-python#24]
Title says it. As of 12.3 Monterey, /usr/bin/python has gone - it needs to be changed to #!/usr/bin/env python3

I've tried that change locally and it seems to work fine, at least with limited testing.

**Comment by gregneagle** [comment]
I’m going with my change here: https://github.com/gregneagle/relocatable-python/commit/4afc5ef09730ac3257250f3ba9a3ccb6046a0ac3

it’s up to the user to set up their environment with an appropriate python. 12.3 ships with _no_ python at all.

**Comment by Keith969** [comment]
Actually it does - /usr/bin/python3.

**Comment by gregneagle** [comment]
Nope. Out of the box, that is _not_ a functional python3 interpreter. No point in breaking all the people who have not yet upgraded to macOS 12.3 and installed either Xcode or the command line development tools.

**Comment by Keith969** [comment]
I must be mistaken then. All I needed to do was change the shebang to python3 and run the script. But whatever, it worked for me and allowed me to build python2 and 3 frameworks that I can distribute with my app.

**Comment by gregneagle** [comment]
You could have also make no changes and done `python3 /path/to/make_relocatable_python_framework.py [options]`
