### ISSUE TITLE
xattr fails to build if using requirements_python3_recommended.txt

### ISSUE THREAD

**Issue by grahampugh** [gregneagle/relocatable-python#30]
It seems that there is a maximum successful version of `xattr`, so if you don't specify one in the requirements.txt file, the build fails. The default version (which fails) of `xattr` is 0.9.9. I have tested 0.9.6 and 0.9.7 and both compile successfully. I haven't gone higher since 0.9.7 is the same version currently specified in the requirements.txt of Munki.

**Comment by erikng** [comment]
think this was meant to be posted on macadmins/slack.

**Comment by erikng** [comment]
I see the issue now. My apologies. :)

**Comment by erikng** [comment]
I got `xattr` to compile now, using something like this: https://github.com/macadmins/python/commit/f58ac5b70e13d26646faa5b0082ee94614507c2e

`export C_INCLUDE_PATH="/Library/Frameworks/Python.framework/Versions/${PYTHON_BIN_VERSION}/include/python${PYTHON_BIN_VERSION}"`

**Comment by gregneagle** [comment]
I believe this has been addressed in the latest commits.

**Comment by gregneagle** [comment]
Closing since no-one has contradicted my last assertion :-)
