### ISSUE TITLE
Invalid signatures in Python.framework

### ISSUE THREAD

**Issue by gregneagle** [gregneagle/relocatable-python#4]
At some point fairly recently, Python.org began signing the Python.framwork in their official downloads (seems like it happened sometime during the 3.8 releases).

Since make_relocatable_python makes modifications to libraries and executables, it breaks the code signing, which then may cause problems elsewhere -- especially with security tools that verify code signing.

One workaround is to resign the bundle yourself with `codesign`, replacing the now invalid signatures with new ones of your own.

But it would be better if the make_relocatable_python removed the invalid signatures. It's arguably better to have _no_ code signatures than _invalid_ code signatures.

**Comment by gregneagle** [comment]
`codesign` has an undocumented `--remove-signature` flag, but some online postings seem to indicate it's undocumented because it's buggy (and therefore not recommended for general use). Still, it might be functional enough to use for this purpose.

**Comment by erikng** [comment]
*watching*. Also FWIW @grahamgilbert did something in his crypt package to handle this.

**Comment by gregneagle** [comment]
Yes, he signs the framework.

**Comment by gaige** [comment]
I discovered this as well when I was using this code to prepare Python 3.8.x for use in Cartographica. The problem I found with leaving it unsigned is that Xcode really doesn't want to re-sign code that isn't signed (oddly enough). As part of my preparation process, I sign the framework and then when I include it in my app it gets re-signed by Xcode (or by my build scripts).

**Comment by gu0keno0** [comment]
Was talking with my colleague nmcspadden about the same issue and created PR https://github.com/gregneagle/relocatable-python/pull/5 which should be able to address the problem :D .

**Comment by gregneagle** [comment]
Addressed with #5.
